package com.github.continuedev.continueeclipseextension.constants;

import java.util.List;

public class MessageTypes {
    public static final List<String> IDE_MESSAGE_TYPES = List.of(
        "readRangeInFile",
        "isTelemetryEnabled",
        "getUniqueId",
        "getWorkspaceConfigs",
        "getDiff",
        "getTerminalContents",
        "getWorkspaceDirs",
        "showLines",
        "writeFile",
        "fileExists",
        "showVirtualFile",
        "openFile",
        "runCommand",
        "saveFile",
        "readFile",
        "showDiff",
        "getOpenFiles",
        "getCurrentFile",
        "getPinnedFiles",
        "getSearchResults",
        "getProblems",
        "subprocess",
        "getBranch",
        "getTags",
        "getIdeInfo",
        "getIdeSettings",
        "getRepoName",
        "listDir",
        "getGitRootPath",
        "getFileStats",
        "insertAtCursor",
        "applyToFile",
        "getGitHubAuthToken",
        "setGitHubAuthToken",
        "getControlPlaneSessionInfo",
        "logoutOfControlPlane",
        "getTerminalContents",
        "showToast",
        "openUrl"
    );

    public static final List<String> PASS_THROUGH_TO_WEBVIEW = List.of(
        "configUpdate",
        "getDefaultModelTitle",
        "indexProgress", // Codebase
        "indexing/statusUpdate", // Docs, etc.
        "addContextItem",
        "refreshSubmenuItems",
        "isContinueInputFocused",
        "didChangeAvailableProfiles",
        "setTTSActive",
        "getWebviewHistoryLength",
        "getCurrentSessionId",
        "docs/suggestions",
        "didCloseFiles",
        "didSelectOrganization"
    );

    public static final List<String> PASS_THROUGH_TO_CORE = List.of(
        "abort",
        "history/list",
        "history/delete",
        "history/load",
        "history/save",
        "devdata/log",
        "config/addModel",
        "config/addContextProvider",
        "config/newPromptFile",
        "config/ideSettingsUpdate",
        "config/getSerializedProfileInfo",
        "config/deleteModel",
        "config/listProfiles",
        "config/refreshProfiles",
        "config/openProfile",
        "config/updateSharedConfig",
        "config/updateSelectedModel",
        "context/getContextItems",
        "context/getSymbolsForFiles",
        "context/loadSubmenuItems",
        "context/addDocs",
        "context/removeDocs",
        "context/indexDocs",
        "autocomplete/complete",
        "autocomplete/cancel",
        "autocomplete/accept",
        "command/run",
        "tts/kill",
        "llm/complete",
        "llm/streamComplete",
        "llm/streamChat",
        "llm/listModels",
        "streamDiffLines",
        "chatDescriber/describe",
        "stats/getTokensPerDay",
        "stats/getTokensPerModel",
        // Codebase
        "index/setPaused",
        "index/forceReIndex",
        "index/forceReIndexFiles",
        "index/indexingProgressBarInitialized",
        // Docs, etc.
        "indexing/reindex",
        "indexing/abort",
        "indexing/setPaused",
        "docs/getSuggestedDocs",
        "docs/initStatuses",
        "docs/getDetails",
        //
        "completeOnboarding",
        "addAutocompleteModel",
        "didChangeSelectedProfile",
        "didChangeSelectedOrg",
        "tools/call",
        "controlPlane/openUrl",
        "controlPlane/listOrganizations"
    );
}
